import healthLeaf from "../../../../assets/img/items_icon/healthLeaf.svg"
import magicalFruit from "../../../../assets/img/items_icon/magicalFruit.svg"
import healthPotion from "../../../../assets/img/items_icon/healthPotion.svg"
import manaPotion from "../../../../assets/img/items_icon/manaPotion.svg"
import ironChain from "../../../../assets/img/items_icon/ironChain.svg"
import gemOfAgility from "../../../../assets/img/items_icon/gemOfAgility.svg"
import gemOfIntelligence from "../../../../assets/img/items_icon/gemOfIntelligence.svg"
import gemOfStrength from "../../../../assets/img/items_icon/gemOfStrength.svg"
import pendantStrength from "../../../../assets/img/items_icon/pendantStrength.svg"
import pendantIntelligence from "../../../../assets/img/items_icon/pendantIntelligence.svg"
import pendantAgility from "../../../../assets/img/items_icon/pendantAgility.svg"
import circlet from "../../../../assets/img/items_icon/circlet.svg"
import { Item } from "../../../../reduxToolkit/slices/items/types"

export const allItems: Item[] = [
    {
        id: 1,
        title: "Health Leaf",
        type: "Consumables",
        description: "The fairy health leaf that restore 70 hp after activation.",
        rarity: "Uncommon",
        passive: false,
        icon: healthLeaf,
        stack: false,
        price: 70,
        active: false,
        healthRestored: 75,
        bonusDamage: 2,
        coolDown: 5,
        manaCost: 0
    },
    {
        id: 2,
        title: "Magical Fruit",
        type: "Consumables",
        description: "The magical fruit that restore 100 mana after activation.",
        rarity: "Uncommon",
        passive: false,
        icon: magicalFruit,
        stack: true,
        price: 70,
        active: false,
        manaRestored: 100,
        hpRegen: 0.5,
        coolDown: 0,
        manaCost: 0
    },
    {
        id: 3,
        title: "Healing Potion",
        type: "Consumables",
        description: "A magical potion that can restore health outside of combat",
        rarity: "Uncommon",
        nonCombat: true,
        passive: false,
        icon: healthPotion,
        stack: true,
        price: 70,
        active: false,
        duration: 10,
        hpRegen: 40,
        coolDown: 0,
        manaCost: 0
    },
    {
        id: 4,
        title: "Large Healing Potion",
        type: "Consumables",
        description: "A magical potion that can restore health outside of combat",
        rarity: "Rare",
        nonCombat: true,
        passive: false,
        icon: healthPotion,
        stack: true,
        price: 500,
        active: false,
        duration: 15,
        hpRegen: 100,
        coolDown: 0,
        manaCost: 0
    },
    {
        id: 5,
        title: "Mana Potion",
        type: "Consumables",
        description: "A mana potion that can restore mana outside of combat",
        rarity: "Uncommon",
        nonCombat: true,
        passive: false,
        icon: manaPotion,
        stack: true,
        price: 50,
        active: false,
        duration: 20,
        manaRegen: 6,
        coolDown: 0,
        manaCost: 0
    },
    {
        id: 6,
        title: "Large Mana Potion",
        type: "Consumables",
        description: "A large mana potion that can restore mana outside of combat",
        rarity: "Rare",
        nonCombat: true,
        passive: false,
        icon: manaPotion,
        stack: true,
        price: 450,
        active: false,
        duration: 20,
        manaRegen: 25,
        coolDown: 0,
        manaCost: 0
    },
    {
        id: 7,
        title: "Iron Chain",
        type: "Attributes",
        description: "A small iron chain that give additional attributes",
        rarity: "Uncommon",
        passive: true,
        icon: ironChain,
        stack: false,
        price: 50,
        active: false,
        strength: 1,
        agility: 1,
        intelligence: 1
    },
    {
        id: 8,
        title: "Gem Of Intelligence",
        type: "Attributes",
        description: "A beautiful gem of wisdom",
        rarity: "Uncommon",
        passive: true,
        craftTo: [12],
        icon: gemOfIntelligence,
        stack: false,
        price: 140,
        active: false,
        intelligence: 3
    },
    {
        id: 9,
        title: "Gem Of Strength",
        type: "Attributes",
        description: "A beautiful gem of strength",
        rarity: "Uncommon",
        passive: true,
        craftTo: [14],
        icon: gemOfStrength,
        stack: false,
        price: 140,
        active: false,
        strength: 3
    },
    {
        id: 10,
        title: "Gem Of Agility",
        type: "Attributes",
        description: "A beautiful gem of agility",
        rarity: "Uncommon",
        passive: true,
        craftTo: [13],
        icon: gemOfAgility,
        stack: false,
        price: 140,
        active: false,
        agility: 3
    },
    {
        id: 11,
        title: "Circlet",
        type: "Attributes",
        description: "Elegant circlet",
        rarity: "Uncommon",
        passive: true,
        icon: circlet,
        craftTo: [12, 13, 14],
        stack: false,
        price: 155,
        active: false,
        agility: 2,
        strength: 2,
        intelligence: 2
    },
    {
        id: 12,
        title: "Pendant of Intelligence",
        type: "Accessories",
        description: "A beautiful gem attached to the pendant, increases intelligence and spell damage",
        rarity: "Rare",
        passive: true,
        requires: [11, 8],
        craft: true,
        recipe: 210,
        icon: pendantIntelligence,
        stack: false,
        price: 510,
        active: false,
        agility: 2,
        strength: 2,
        intelligence: 5,
        manaRegen: 0.6,
        spellAmp: 3
    },
    {
        id: 13,
        title: "Pendant of Agility",
        type: "Accessories",
        description: "A beautiful gem attached to the pendant, increases agility, armor and attack speed",
        rarity: "Rare",
        passive: true,
        craft: true,
        requires: [11, 10],
        recipe: 210,
        icon: pendantAgility,
        stack: false,
        price: 510,
        active: false,
        agility: 5,
        strength: 2,
        intelligence: 2,
        armor: 2,
        attackSpeed: 5
    },
    {
        id: 14,
        title: "Pendant of Strength",
        type: "Accessories",
        description:
            "A beautiful gem attached to the pendant, increases strength, health regeneration and attack damage",
        rarity: "Rare",
        passive: true,
        craft: true,
        requires: [11, 9],
        recipe: 210,
        icon: pendantStrength,
        stack: false,
        price: 510,
        active: false,
        agility: 2,
        strength: 5,
        intelligence: 2,
        bonusDamage: 3,
        hpRegen: 1
    }
]
